// ═══════════════════════════════════════════════════════════════════════════════
// VISUAL ENHANCER (Sprint 13) — Auto-inject scroll animations + premium polish
// into HTML files generated by Code Engine
// ═══════════════════════════════════════════════════════════════════════════════

import type { StagedCommand } from './transaction-manager'

// ─── Scroll Animation CSS + JS injection ─────────────────────────────────────

const SCROLL_ANIMATION_CSS = `
/* ═══ Octopus Visual Enhancer — Scroll Animations ═══ */
.animate-on-scroll {
  opacity: 0;
  transform: translateY(30px);
  transition: opacity 0.7s cubic-bezier(0.4, 0, 0.2, 1), transform 0.7s cubic-bezier(0.4, 0, 0.2, 1);
}
.animate-on-scroll.visible {
  opacity: 1;
  transform: translateY(0);
}
.animate-on-scroll:nth-child(2) { transition-delay: 0.1s; }
.animate-on-scroll:nth-child(3) { transition-delay: 0.2s; }
.animate-on-scroll:nth-child(4) { transition-delay: 0.3s; }
.animate-on-scroll:nth-child(5) { transition-delay: 0.4s; }
.animate-on-scroll:nth-child(6) { transition-delay: 0.5s; }
`

const SCROLL_ANIMATION_JS = `
/* ═══ Octopus Visual Enhancer — IntersectionObserver ═══ */
(function() {
  const observer = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1, rootMargin: '0px 0px -50px 0px' });

  function initAnimations() {
    document.querySelectorAll('.animate-on-scroll').forEach(function(el) {
      observer.observe(el);
    });
    // Auto-detect sections without the class and add it
    document.querySelectorAll('section, [class*="section"], .card, .pricing-card, .feature-card, .faq-item').forEach(function(el) {
      if (!el.classList.contains('animate-on-scroll') && !el.classList.contains('visible')) {
        el.classList.add('animate-on-scroll');
        observer.observe(el);
      }
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAnimations);
  } else {
    initAnimations();
  }
})();
`

// ─── Smart Section Detection + Class Addition ───────────────────────────────

function addAnimateClassToSections(html: string): string {
  // Add animate-on-scroll to <section> tags that don't already have it
  let result = html
  
  // Add to <section> tags
  result = result.replace(
    /<section\b([^>]*?)(?<!animate-on-scroll)>/gi,
    (match, attrs) => {
      if (attrs.includes('animate-on-scroll')) return match
      if (attrs.includes('class="')) {
        return match.replace(/class="/, 'class="animate-on-scroll ')
      }
      if (attrs.includes("class='")) {
        return match.replace(/class='/, "class='animate-on-scroll ")
      }
      return `<section class="animate-on-scroll"${attrs}>`
    }
  )
  
  return result
}

// ─── Check if HTML already has scroll animations ─────────────────────────────

function hasScrollAnimations(html: string): boolean {
  return html.includes('IntersectionObserver') ||
    html.includes('animate-on-scroll') ||
    html.includes('scroll-animation') ||
    html.includes('aos-init') || // AOS library
    html.includes('data-aos') ||
    html.includes('scrollreveal')
}

// ─── Main injection function ─────────────────────────────────────────────────

export function injectScrollAnimations(html: string): { html: string; modified: boolean } {
  // Skip if already has scroll animations
  if (hasScrollAnimations(html)) {
    return { html, modified: false }
  }
  
  // Skip non-HTML or very small files
  if (!html.includes('<html') && !html.includes('<body') && !html.includes('<section')) {
    return { html, modified: false }
  }
  
  let result = html
  let modified = false
  
  // Step 1: Add animate-on-scroll classes to sections
  result = addAnimateClassToSections(result)
  
  // Step 2: Inject CSS before </head> or at start of <style>
  if (result.includes('</head>')) {
    result = result.replace('</head>', `<style>${SCROLL_ANIMATION_CSS}</style>\n</head>`)
    modified = true
  } else if (result.includes('<style>')) {
    // Prepend to first <style> block
    result = result.replace('<style>', `<style>${SCROLL_ANIMATION_CSS}`)
    modified = true
  }
  
  // Step 3: Inject JS before </body>
  if (result.includes('</body>')) {
    result = result.replace('</body>', `<script>${SCROLL_ANIMATION_JS}</script>\n</body>`)
    modified = true
  } else {
    // Append at end
    result += `\n<script>${SCROLL_ANIMATION_JS}</script>`
    modified = true
  }
  
  return { html: result, modified }
}

// ─── Auto-Responsive Verification (Sprint 13 #6) ─────────────────────────────
// Ensures all HTML output has viewport meta + basic responsive fallback CSS

const RESPONSIVE_FALLBACK_CSS = `
/* ═══ Octopus Visual Enhancer — Responsive Fallback ═══ */
@media (max-width: 768px) {
  body { overflow-x: hidden; }
  img, video, iframe { max-width: 100%; height: auto; }
  .container, [class*="container"] { padding-left: 1rem; padding-right: 1rem; }
  h1 { font-size: 2rem !important; }
  h2 { font-size: 1.5rem !important; }
  .grid { grid-template-columns: 1fr !important; }
  .flex-row-desktop { flex-direction: column !important; }
  table { display: block; overflow-x: auto; }
}
@media (max-width: 480px) {
  h1 { font-size: 1.6rem !important; }
  h2 { font-size: 1.25rem !important; }
  section, [class*="section"] { padding: 2rem 1rem !important; }
}
`

const VIEWPORT_META = '<meta name="viewport" content="width=device-width, initial-scale=1.0">'

export function injectResponsiveDefaults(html: string): { html: string; modified: boolean } {
  // Skip non-HTML files
  if (!html.includes('<html') && !html.includes('<head') && !html.includes('<body')) {
    return { html, modified: false }
  }

  let result = html
  let modified = false

  // Step 1: Inject viewport meta if missing
  const hasViewport = /meta[^>]+viewport/i.test(result)
  if (!hasViewport) {
    if (result.includes('<head>')) {
      result = result.replace('<head>', `<head>\n  ${VIEWPORT_META}`)
      modified = true
    } else if (result.includes('<head ')) {
      result = result.replace(/<head\s[^>]*>/, (match) => `${match}\n  ${VIEWPORT_META}`)
      modified = true
    } else if (result.includes('<html')) {
      // No <head> at all — inject one
      result = result.replace(/<html[^>]*>/, (match) => `${match}\n<head>\n  ${VIEWPORT_META}\n</head>`)
      modified = true
    }
  }

  // Step 2: Inject responsive fallback CSS if no @media rules detected
  const hasMediaQueries = /@media\s*\(/i.test(result)
  if (!hasMediaQueries) {
    if (result.includes('</head>')) {
      result = result.replace('</head>', `<style>${RESPONSIVE_FALLBACK_CSS}</style>\n</head>`)
      modified = true
    } else if (result.includes('</body>')) {
      result = result.replace('</body>', `<style>${RESPONSIVE_FALLBACK_CSS}</style>\n</body>`)
      modified = true
    }
  }

  return { html: result, modified }
}

// ─── Apply to staged commands (called from chat route) ──────────────────────

export function applyVisualEnhancements(
  stagedCommands: StagedCommand[],
): { updatedCommands: StagedCommand[]; enhancedFiles: string[] } {
  const enhancedFiles: string[] = []
  
  const updatedCommands = stagedCommands.map(cmd => {
    if (cmd.type !== 'write_file') return cmd
    const path = (cmd.payload as { path?: string }).path || ''
    if (!/\.html?$/i.test(path)) return cmd
    
    let content = (cmd.payload as { content?: string }).content || ''
    let anyModified = false

    // 1. Scroll animations
    const scroll = injectScrollAnimations(content)
    if (scroll.modified) { content = scroll.html; anyModified = true }

    // 2. Responsive defaults (viewport + fallback CSS)
    const responsive = injectResponsiveDefaults(content)
    if (responsive.modified) { content = responsive.html; anyModified = true }

    if (anyModified) {
      enhancedFiles.push(path)
      return {
        ...cmd,
        payload: { ...(cmd.payload as object), content },
      }
    }
    return cmd
  })
  
  return { updatedCommands, enhancedFiles }
}

// ─── Apply image generation integration (Sprint 13 #3) ─────────────────────
// Detect broken external image URLs and suggest generate_image instead

const BROKEN_IMAGE_PATTERNS = [
  /cdn\.spline\.design/i,
  /unsplash\.com\/photos/i,
  /via\.placeholder\.com/i,
  /placehold\.co/i,
  /placekitten\.com/i,
  /picsum\.photos/i,
  /lorempixel\.com/i,
  /dummyimage\.com/i,
]

export function detectBrokenImageUrls(html: string): string[] {
  const brokenUrls: string[] = []
  const imgRegex = /<img[^>]+src=["']([^"']+)["'][^>]*>/gi
  let match
  while ((match = imgRegex.exec(html)) !== null) {
    const url = match[1]
    // Skip data URIs and relative paths
    if (url.startsWith('data:') || !url.startsWith('http')) continue
    // Check against known problematic patterns
    if (BROKEN_IMAGE_PATTERNS.some(p => p.test(url))) {
      brokenUrls.push(url)
    }
  }
  return brokenUrls
}
