// ============================================
// 👁️🔄 SELF-REVIEW — Visual Reflexion Loop
// ============================================
// After Code Engine generates files, this skill:
// 1. Serves the combined HTML at a public URL
// 2. Captures a screenshot of the rendered output
// 3. Sends it to Vision LLM to detect visual issues
// 4. Returns structured feedback for auto-fix
// ============================================

import { callLLM } from '@/lib/turbo-llm'
import { generatePreviewToken } from '@/lib/preview-token'

// ── Types ──
export interface ReviewIssue {
  severity: 'critical' | 'major' | 'minor' | 'suggestion'
  area: string        // e.g. "Hero section", "Navbar", "Color contrast"
  description: string // What's wrong
  fix: string         // Suggested CSS/HTML fix
}

export interface SelfReviewResult {
  score: number         // 0-100 overall quality score
  passed: boolean       // true if score >= 75 and no critical issues
  issues: ReviewIssue[]
  praise: string[]      // What looks good
  summary: string       // One-line summary
  fixActions?: string   // Optional: pre-built write_file action block for auto-fix
}

// ── Screenshot Capture for Self-Review ──
async function capturePreviewScreenshot(
  previewUrl: string,
): Promise<Buffer | null> {
  // Use microlink.io to screenshot the preview URL
  try {
    const mlParts = ['https:', '', 'api.microlink.io']
    const mlBase = mlParts.join('/')
    const apiUrl = mlBase + '/?url=' + encodeURIComponent(previewUrl) + '&screenshot=true&meta=false&waitFor=2000'
    
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 30000)
    
    const res = await fetch(apiUrl, { signal: controller.signal })
    clearTimeout(timeout)
    
    if (!res.ok) {
      console.warn(`[SelfReview] Microlink HTTP ${res.status}`)
      return null
    }
    
    const json = await res.json() as { status: string; data?: { screenshot?: { url?: string } } }
    const ssUrl = json?.data?.screenshot?.url
    if (!ssUrl) {
      console.warn('[SelfReview] No screenshot URL from microlink')
      return null
    }
    
    // Download the screenshot image
    const imgRes = await fetch(ssUrl)
    if (!imgRes.ok) return null
    const buffer = Buffer.from(await imgRes.arrayBuffer())
    if (buffer.length < 5000) {
      console.warn(`[SelfReview] Screenshot too small: ${buffer.length} bytes`)
      return null
    }
    
    console.log(`[SelfReview] Screenshot captured: ${(buffer.length / 1024).toFixed(0)}KB`)
    return buffer
  } catch (err) {
    console.warn(`[SelfReview] Screenshot failed: ${err instanceof Error ? err.message : err}`)
    return null
  }
}

// ── Vision Review Prompt ──
const SELF_REVIEW_PROMPT = `You are a senior frontend QA engineer performing a visual review of a web page.
You are looking at a screenshot of code that was JUST generated by an AI code engine.

Your job is to find VISUAL ISSUES that a human would notice:

1. **Layout problems**: Overlapping elements, broken grids, content overflow, misalignment
2. **Color/contrast issues**: Unreadable text, wrong backgrounds, colors that clash
3. **Missing content**: Empty sections, broken images (shown as broken icons), placeholder text still visible
4. **Typography issues**: Text too small/large, wrong fonts loaded, inconsistent sizing
5. **Responsive concerns**: Elements that look squeezed or stretched
6. **Visual polish**: Spacing inconsistencies, missing hover states, rough edges

Do NOT flag:
- Placeholder images from external CDNs (unsplash, picsum, etc.) — these are fine
- Minor text content choices
- Missing favicon

Respond in JSON format:
{
  "score": <0-100 quality score>,
  "passed": <true if score >= 75>,
  "issues": [
    {
      "severity": "critical" | "major" | "minor" | "suggestion",
      "area": "<which part of the page>",
      "description": "<what’s wrong>",
      "fix": "<specific CSS/HTML fix>"
    }
  ],
  "praise": ["<what looks good>"],
  "summary": "<one-line overall assessment>"
}`

// ── Main Review Function ──
export async function performSelfReview(
  sessionId: string,
  userId: string,
  userMessage?: string,
): Promise<SelfReviewResult | null> {
  const start = Date.now()
  
  // Build the preview URL
  const baseUrl = process.env.NEXTAUTH_URL || 'http://localhost:3000'
  const token = generatePreviewToken(sessionId)
  const previewUrl = `${baseUrl}/api/arms/claude-code/preview-render?sessionId=${sessionId}&token=${token}`
  
  console.log(`[SelfReview] Starting visual review for session ${sessionId.substring(0, 8)}...`)
  console.log(`[SelfReview] Preview URL: ${previewUrl.substring(0, 80)}...`)
  
  // Capture screenshot
  const screenshot = await capturePreviewScreenshot(previewUrl)
  if (!screenshot) {
    console.warn('[SelfReview] Could not capture screenshot — skipping review')
    return null
  }
  
  const base64 = `data:image/png;base64,${screenshot.toString('base64')}`
  
  // Build context for the review
  const contextNote = userMessage
    ? `The user asked: "${userMessage.substring(0, 200)}"\nReview how well the output matches this request.`
    : 'Review the general quality of this generated web page.'
  
  // Send to Vision LLM
  const messages = [
    { role: 'system', content: SELF_REVIEW_PROMPT },
    {
      role: 'user',
      content: [
        { type: 'text', text: `${contextNote}\n\nAnalyze this screenshot and provide your QA review:` },
        { type: 'image_url', image_url: { url: base64 } },
      ],
    },
  ]
  
  const result = await callLLM(userId, messages, {
    model: 'gpt-4.1',
    temperature: 0.2,
    maxTokens: 3000,
  })
  
  const raw = result.choices?.[0]?.message?.content || ''
  const duration = Date.now() - start
  console.log(`[SelfReview] Analysis completed in ${duration}ms (${raw.length} chars)`)
  
  // Parse JSON response
  let jsonStr = raw
  const jsonMatch = raw.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (jsonMatch) jsonStr = jsonMatch[1]
  
  const braceStart = jsonStr.indexOf('{')
  const braceEnd = jsonStr.lastIndexOf('}')
  if (braceStart >= 0 && braceEnd > braceStart) {
    jsonStr = jsonStr.slice(braceStart, braceEnd + 1)
  }
  
  try {
    const parsed = JSON.parse(jsonStr) as SelfReviewResult
    console.log(`[SelfReview] Score: ${parsed.score}/100, Issues: ${parsed.issues?.length || 0}, Passed: ${parsed.passed}`)
    return {
      score: parsed.score || 50,
      passed: parsed.passed ?? (parsed.score >= 75),
      issues: parsed.issues || [],
      praise: parsed.praise || [],
      summary: parsed.summary || 'Review completed',
    }
  } catch (parseErr) {
    console.error('[SelfReview] Failed to parse review JSON:', parseErr)
    return {
      score: 70,
      passed: true,
      issues: [],
      praise: ['Page renders successfully'],
      summary: 'Review completed (could not parse detailed feedback)',
    }
  }
}

// ── Format review as context for LLM auto-fix ──
export function formatReviewForLLM(review: SelfReviewResult): string {
  if (!review.issues || review.issues.length === 0) return ''
  
  const criticalAndMajor = review.issues.filter(i => i.severity === 'critical' || i.severity === 'major')
  if (criticalAndMajor.length === 0) return '' // Only fix critical/major issues
  
  let ctx = `\n[SELF_REVIEW — Visual QA Score: ${review.score}/100]\n`
  ctx += `Summary: ${review.summary}\n`
  ctx += `Issues requiring fixes:\n`
  
  for (const issue of criticalAndMajor) {
    ctx += `- [${issue.severity.toUpperCase()}] ${issue.area}: ${issue.description}\n`
    ctx += `  Fix: ${issue.fix}\n`
  }
  
  ctx += `\nGenerate write_file actions to fix these issues. Only modify the affected files.\n`
  return ctx
}
